### ISSUE TITLE
windows终端命令行下如何使用代理？

### ISSUE THREAD

**Issue by anlexN** [shadowsocksr-rm/shadowsocksr-csharp#2]
代理已经成功，浏览器也能访问被限制的网站，就是终端不能！我要网上相关资料：set http_proxy=127.0.0.1:1080, 还是无法设置！！！

**Comment by RightFS** [comment]
看你用什么软件,那软件不支持代理,你怎么设置都白搭。可以用proxifier搞定,免费的有个sockscap

**Comment by 1265578519** [comment]
sstap
